# Compose CI pipeline
x-documentation: >
  # Compose CI:

  ## Requirements

  ## Start the CI pipeline

  ```bash
  docker compose -f 08.compose.ci.cagent.yml up --build
  docker compose -f 08.compose.ci.cagent.yml down -v
  ```
  > you can even use the watch mode to test and debug your CI pipeline.

  ## About variable interpolation

  - https://docs.docker.com/reference/compose-file/interpolation/

services:

  mcp-gateway:
    image: docker/mcp-gateway:v2
    # ports:
    #   - 9011:9011
    use_api_socket: true
    command:
      - --port=9011
      - --transport=streaming
      - --verbose
      - --catalog=/mcp/catalog.yaml
      - --servers=mcp-files

    configs:
      - source: catalog.yaml
        target:
          /mcp/catalog.yaml
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      mcp-files:
        condition: service_healthy

  mcp-files:
    # GitHub repository: git@github.com:micro-agent/mcp-files-server.git
    image: k33g/mcp-files-server:0.0.3
    environment:
      MCP_HTTP_PORT: 6060
      LOCAL_WORKSPACE_FOLDER: /app
    volumes:
      - ./reports:/app/reports
      - ./cracker-runner:/app/cracker-runner
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:6060/health"]
      interval: 30s
      timeout: 30s
      retries: 5
      start_period: 40s

  ci-agent:
    image: docker/cagent:1.9.7
    volumes:
      - ./ai-ci-agent.yaml:/app/ai-ci-agent.yaml
    command: 
      - exec
      - /app/ai-ci-agent.yaml
      - --yolo
      - |
        Read and analyze /reports/cves.report.text, 
        then generate a file (/reports/analyze.md) with 
        a summary of the vulnerabilities found in the image 
        along with recommendations to fix them.
    tty: true
    stdin_open: true    
    
    models:
      #- qwen
      - jan-nano

    depends_on:
      mcp-gateway:
        condition: service_started
      # image-vulnerability-scan:
      #   condition: service_completed_successfully


  stop-mcp-servers:
    image: docker:cli
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command:
      - /bin/sh
      - -c
      - |  
        docker stop cracker-mcp-files-1
        docker stop cracker-mcp-gateway-1
    depends_on:
      ci-agent:
        condition: service_completed_successfully

models:

  # qwen:
  #   model: ai/qwen2.5:latest

  jan-nano:
    model: hf.co/menlo/jan-nano-gguf:q4_k_m

  # coder-model:
  #   model: hf.co/qwen/qwen2.5-coder-3b-instruct-gguf:q4_k_m

configs:
  catalog.yaml:
    content: |
      registry:

        mcp-files:
          remote:
            url: "http://mcp-files:6060/mcp"
            transport_type: http
